version: '3'
services:
  backend:
    build:
      context: ./backend
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    command: bash -c "composer install && touch ./database/database.sqlite && cp .env.example .env &&  php artisan migrate && php artisan serve  --host 0.0.0.0 --port 8000"
    expose:
      - 8000
    ports:
      - 8000:8000
  frontend:
    image: node:14
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/home/node/app
    expose:
      - 8080
    ports:
      - 8080:8080
    command: bash -c "npm install && npm run dev"
  web:
    image: nginx:alpine
    volumes:
      - ./:/var/www/html
      - ./.docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
