version: '3'
services:
  backend:
    image: php:7.4-fpm
    #build:
    #  context: ./.docker
    volumes:
      #- ./.docker/config/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./backend:/var/www/html
    command: bash -c "composer install & php artisan serve"
    expose:
      - 8000
    depends_on:
      - web
  web:
    image: nginx:alpine
    volumes:
      - ./:/var/www/html
      - ./.docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  frontend:
    image: node:14
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/home/node/app
    expose:
      - 8080
    command: bash -c "npm install && npm run dev"
    depends_on:
      - web
